[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
